### ISSUE TITLE
Error: Order amount too low

### ISSUE THREAD

**Issue by piavgh** [tomochain/dex-server#5]
This error happens when user submits new order (clicking on Buy/Sell buttons)

Parameters sent from client code:

```
amount: "5000000000000000000000"
baseToken: "0x7D2d3073EaB94BA50F83A60Cea14020F0C906Da0"
exchangeAddress: "0xc1F424996039cc5B037dfB073bcd6e6915F0dfab"
hash: "0xd403dcc32af59560b96355fbd5170c34e7484275715bc4144e5c160209a655c1"
makeFee: "0"
nonce: "7064685038749838"
pricepoint: "1000000"
quoteToken: "0x53DDd545882dec853226dC8255268C7760276695"
side: "BUY"
signature:
    r: "0x236d83fde81312f5053192b9a660b59ff15e9ad28c59a2684d45a2d0953d872f"
    s: "0x49afa76ed61bd8b9f6d3964bc23d228999a8f274c3e64451d3c01b015cbc5344"
    v: 27
__proto__: Object
status: "NEW"
takeFee: "0"
userAddress: "0x28074f8D0fD78629CD59290Cac185611a8d60109"
```

Server returns error `Error: Order amount too low`

Please check to see why server returns this error.
